#!/usr/bin/env php
<?php

namespace Yuloh\JsonGuardCli;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

use Silly\Application;
use Yuloh\JsonGuardCli\Commands;

$app = new Application('JSON Guard CLI', '0.0.1');

$app
    ->command('validate [data] [schema]', new Commands\Validate())
    ->descriptions(
        'Validate JSON data against a schema',
        [
            'data' => 'The data to validate.',
            'schema' => 'The schema to use.'
        ]
    );

$app
    ->command('check [schema]', new Commands\Check())
    ->descriptions(
        'Check that a JSON Schema is valid.',
        [
            'schema' => 'The schema to check.'
        ]
    );

$app->run();
